### ISSUE TITLE
Reproduce the results

### ISSUE THREAD

**Issue by Pengwei-Jin** [mojivalipour/symbolicgpt#3]
Hi, I tried to reproduce the results for 2 variables model but got a worse result shown in the image
![XYE_2Var_200-201Points_512EmbeddingSize_SymbolicGPT_GPT_PT_EMB_SUM_Skeleton_Padding_NOT_VAR_MINIMIZE](https://user-images.githubusercontent.com/84560451/179383145-36013fb2-1636-4f18-9253-c314c1eed90f.png)
. I just downloaded the datasets and retrained the model using parameters provided in README.  So, is there any detail I haven't noticed?

**Comment by mojivalipour** [comment]
Please let me know more about the config of the computer that you trained with such as GPU etc. Did you train the model for 20 epochs?

**Comment by Pengwei-Jin** [comment]
Hi, I retrained the model for 20 epochs twice and both got the same results with you. Maybe something unexpected occurred for the first time. Thank you for your reply. : )
